In [2]:
from TAFKAP import TAFKAP_decode
import time
# TAFKAP_decode(None, {'randseed': 455, 'stim_type':'circular', 'prev_C':True})
# TAFKAP_decode(None, {'randseed': 455, 'stim_type':'categorical', 'prev_C':True})
t1 = time.perf_counter()
est, unc, liks, hypers = TAFKAP_decode(None, {'randseed': 1234, 'stim_type':'circular', 'prev_C':False})
t2 = time.perf_counter()
print(t2-t1)

#159 seconds with gpu acc
#326 seconds on cpu


--SIMULATING DATA--
--PERFORMING HYPERPARAMETER SEARCH--
--GRID SEARCH--
00/56 -- lambda_var: 0.00, lambda: 0.02, loss: 302.421
01/56 -- lambda_var: 0.00, lambda: 0.18, loss: 23.1965
02/56 -- lambda_var: 0.00, lambda: 0.35, loss: 9.91214
03/56 -- lambda_var: 0.00, lambda: 0.51, loss: 6.03038
04/56 -- lambda_var: 0.00, lambda: 0.67, loss: 4.46115
05/56 -- lambda_var: 0.00, lambda: 0.84, loss: 3.79567
06/56 -- lambda_var: 0.00, lambda: 1.00, loss: 3.83516
07/56 -- lambda_var: 0.14, lambda: 0.02, loss: 301.315


KeyboardInterrupt: 

In [6]:
import numpy as np
a = np.ones((10,2))
print(a)
print(type(a))
if type(a) is np.ndarray:
    print('foo')

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
<class 'numpy.ndarray'>
foo


In [22]:
from TAFKAP import invSNC
from scipy.io import savemat
torch.set_default_dtype(torch.float64)

W, tau, sig, rho = torch.randn(100,8), torch.randn(100)*0.05+0.7, torch.tensor(0.3), torch.tensor(0.05)
omi, ld = invSNC(W, tau, sig, rho, True)
print(ld,omi)

savemat('foo.mat', {'W':W.numpy(), 'tau':tau.numpy(), 'sig':sig.item(), 'rho':rho.item(), 'ld':ld.item(), 'omi':omi.numpy()})


tensor(-51.5237) tensor([[ 2.1288, -0.0320,  0.0485,  ...,  0.0130,  0.0652, -0.0780],
        [-0.0320,  1.5426, -0.0239,  ..., -0.0646, -0.0678, -0.0761],
        [ 0.0485, -0.0239,  1.7385,  ..., -0.0494, -0.1275,  0.0564],
        ...,
        [ 0.0130, -0.0646, -0.0494,  ...,  1.7425, -0.0950, -0.0263],
        [ 0.0652, -0.0678, -0.1275,  ..., -0.0950,  1.8430, -0.0022],
        [-0.0780, -0.0761,  0.0564,  ..., -0.0263, -0.0022,  1.8975]])


In [20]:
import torch
print(torch.cuda.is_available())
torch.manual_seed(1234)
a = torch.randn(100, 1000,1000)
a = torch.bmm(a,a.transpose(1,2)) + torch.eye(1000).unsqueeze(0)*0.1
print(a.shape)

%timeit a.inverse()
a = a.cuda()
%timeit torch.cholesky_inverse(torch.linalg.cholesky(a))


True
torch.Size([100, 1000, 1000])
1.15 s ± 73.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
785 ms ± 10.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [38]:
import torch
torch.set_default_tensor_type('torch.cuda.FloatTensor')
a = torch.randn(10,3)
b = torch.randn(3,8)

c  = a @ b

print(c.shape)
print(a[(2,),:].shape)
print(a.device)

torch.Size([10, 8])
torch.Size([1, 3])
cuda:0


In [32]:
print((99+1)%100)

0


In [2]:
%debug

> c:\users\ruben\anaconda3\lib\site-packages\torch\_tensor.py(561)__format__()
    559         if self.dim() == 0:
    560             return self.item().__format__(format_spec)
--> 561         return object.__format__(self, format_spec)
    562 
    563     def __ipow__(self, other):  # type: ignore[misc]

> c:\users\ruben\dropbox\tafkap\tafkap\tafkap.py(160)find_lambda()
    158 
    159             best_lambda = torch.Tensor((grid_l1[best_idx], grid_l2[best_idx]))
--> 160             print("Best setting found: lambda_var = {:3.2f}, lambda = {:3.2f}, loss: {:g}".format(*best_lambda, best_loss))
    161 
    162 

tensor([0.6327, 0.7551])
tensor([4.6850])
Best setting found: lambda_var = 0.63, lambda = 0.76, loss: 4.68495


In [ ]:
# from TAFKAP import sub2ind

def sub2ind(sz, row, col):
    n_rows = sz[0]    
    return [n_rows * (c) + r for r, c in zip(row, col)]

sub2ind((10,4), (8-1,), (2-1,))

In [ ]:
import torch
a = torch.randn(2)
print('{:02d}: {:3.2f} and {:5.4g}'.format(a.numel(), *a))

In [ ]:
print('{:}{:02d}, {:3.2f}'.format(3, 5.3234))

In [ ]:
%debug


In [ ]:
import torch
C = torch.randn(1000,1000)
C = torch.mm(C,C.t())
a = torch.logdet(C)
print(C.is_complex())


In [ ]:
a = 5
print(a.is_complex())

In [ ]:
%debug

In [9]:
import torch
a = torch.randint(4, (5,))
print(a)

b,c = a.min(0)
print(b,c)


tensor([1, 3, 3, 3, 2])
tensor(1) tensor(0)


In [ ]:
pp = 8
print((pp,)*2)

In [ ]:
a,b,c = [],[],[]
a.append(4)
print(b)

In [ ]:
%debug

In [ ]:
import torch
from numpy import pi
a = torch.linspace(0, 2*pi, 10)
print(a)
b = (torch.rand(5)*(0*2*pi/10)).unsqueeze(1)
print(b)
c = a+b
print(c)

for j in range(5):
    c[j][:] = c[j][torch.randperm(10)]

print(c)
print(c.sum(1))
c =c.ravel()
print(c)
print(c.T)
print(c.shape[0])

In [ ]:
from TAFKAP import fun_basis
import torch
from matplotlib import pyplot as plt
from numpy import pi

x = torch.randint(0, 4, (100,1))
y = fun_basis(x, None, None, torch.arange(4))
print(y.shape)
print(y)
plt.plot(x,y)


In [ ]:
from TAFKAP import makeSNCData
makeSNCData({'sim_stim_type':'categorical'})

In [ ]:
import torch
a = torch.randint(10,(10,))
print(a)
print((a==a.int()).all())


In [ ]:
%debug


In [ ]:
import torch
a = torch.randn(10)
b = a>0
print(b)
print(b.logical_not())

In [ ]:
%debug

In [ ]:
from TAFKAP import makeSNCData

In [ ]:
import numpy as np
tmp = np.tile(np.arange(5),(5,1))
print(tmp[1])

In [ ]:
import numpy as np
a = np.arange(10)
print(a)
tmp = (a*np.expand_dims(a,1))
print(tmp)
print(tmp.shape)

In [ ]:
%debug

In [ ]:
import numpy as np
a = np.linspace(0,1,7)
b = np.arange(0,10)
np.random.seed(1234)
print(a)
c = np.expand_dims(a,1)+b
print(c)
print('foo')
print(c.shape)
np.random.shuffle(c.T)
print(c)
print(c.ravel())